/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOANGULARFUNC
#define ROOANGULARFUNC

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooAngularFunc : public RooAbsReal {
public:
  RooAngularFunc() {} ; 
  RooAngularFunc(const char *name, const char *title,
	      RooAbsReal& _Fl,
	      RooAbsReal& _S3,
	      RooAbsReal& _S4,
	      RooAbsReal& _S5,
	      RooAbsReal& _S6,
	      RooAbsReal& _S7,
	      RooAbsReal& _S8,
	      RooAbsReal& _S9,
	      RooAbsReal& _thetaK,
	      RooAbsReal& _thetaL,
	      RooAbsReal& _phi);
  RooAngularFunc(const RooAngularFunc& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooAngularFunc(*this,newname); }
  inline virtual ~RooAngularFunc() { }

protected:

  RooRealProxy Fl ;
  RooRealProxy S3 ;
  RooRealProxy S4 ;
  RooRealProxy S5 ;
  RooRealProxy S6 ;
  RooRealProxy S7 ;
  RooRealProxy S8 ;
  RooRealProxy S9 ;
  RooRealProxy thetaK ;
  RooRealProxy thetaL ;
  RooRealProxy phi ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooAngularFunc,1) // Your description goes here...
};
 
#endif
